challenge:
  enabled: true
  period: weekly      # what period?
  run-day: MONDAY     # day-of-week for auto run
  run-time: "18:55" # 0â€“23, 24 hour time, based on your server host location
  # run-hour: 18         # legacy - only use if errors

  broadcast-msg: true # send broadcast when a new rich man is chosen
  broadcast-on-join: true # broadcast the current rich man to new players

  reward-commands:
    - "lp user {player} parent addtemp richman 7d"

messages:
  prefix: "&8[&6&lRich Man&8] &7"
  no-winner: "No Rich Man has been crowned yet."
  last-winner: "&e{player} &7with &a${amount}&7."
  running: "Selecting this week's Rich Man..."
  winner-line: "&aRich Man winner: &6{player} &7with &a${amount}&7."
  no-permission: "&cYou don't have permission to do that."
  broadcast: "&6[&lRich Man&r&6] &e{player} &7is this week's &eRich Man &7with &a${amount}&7!"
  reminder: "&6&l[Rich Man]&r&e A new Rich Man in &b{time_left}&e. Use &a/richman info &efor how to win."

  # Formatting for the /richman dashboard
  header: "&6&l====[ Rich Man ]===="
  next-run: "&7Next selection in &f{time_left} &7(on &f{datetime}&7)"
  usage: "&7Use &e/richman top &7to view the top balances."

  # Formatting for /richman top
  top-header: "&6&lRich Man Top Balances &7(Page {page}/{pages})"
  top-line: "&7#{position} &f{player} &a${amount}"
  top-footer: "&7Use &e/richman top {prev} &7or &e/richman top {next}&7 to change page."
  top-empty: "&7No players have any balance yet."

  economy-not-ready: "&cEconomy is not ready. Please contact an admin."

countdown:
  enabled: true
  hourly:
    start-hours-before: 6
    message: "&7A new &6&lRich Man &r&fwill be drawn &etoday&f! Get your &amoney &fup."
  hour-before:
    message: "&6&lRich Man &r&eevent in &61 hour&f! &aSell &fyour stuff now!"
  minute-5:
    message: "&6&lRich Man &r&eevent in &65 minutes&f!"
  minute-1:
    message: "&6&lRich Man &r&eevent in &61 minute&f!"
  second-30:
    message: "&6&lRich Man &r&eevent in &630 seconds&f! Make sure you remember to &asell&f!"
  final-10:
    message: "&6&lRich Man &r&ein &6&l%seconds%s&r&f...!"